#ifndef _VCF_DRAGSCROLLEVENT_H__
#define _VCF_DRAGSCROLLEVENT_H__
//DragScrollEvent.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */




namespace VCF{

class APPLICATIONKIT_API DragScrollEvent : public Event {
public:
    DragScrollEvent( Object* source, uint32 eventType ): Event( source, eventType ) {}
};

};


#endif // _VCF_DRAGSCROLLEVENT_H__

/**
$Id$
*/
