#ifndef _VCF_SCROLLEVENT_H__
#define _VCF_SCROLLEVENT_H__
//ScrollEvent.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */



namespace VCF{
/**
\class ScrollEvent ScrollEvent.h "vcf/ApplicationKit/ScrollEvent.h"
*/
class APPLICATIONKIT_API ScrollEvent : public VCF::Event {
public:
    ScrollEvent( Object* source, const uint32& eventType ) : Event(source,eventType) {}

	ScrollEvent( const ScrollEvent& rhs ):Event(rhs) {
		*this = rhs;
	}

	ScrollEvent& operator=( const ScrollEvent& rhs ) {
		Event::operator =( rhs );
		scrollPt_ = rhs.scrollPt_;

		return *this;
	}
    Point getScrollPoint() const {
        return scrollPt_;
    }

    void setScrollPoint( const Point& pt ) {
        scrollPt_ = pt;
    }

	virtual Object* clone( bool deep=false ) {
		return new ScrollEvent(*this);
	}
protected:
    Point scrollPt_;
};


/**
*/
typedef Delegate1<ScrollEvent*> ScrollDelegate; 
typedef ScrollDelegate::ProcedureType ScrollHandler;



};


#endif // _VCF_SCROLLEVENT_H__

/**
$Id$
*/
