#!/usr/bin/bash

VERSION=`cat ../VERSION`

echo Preparing list of files for vcf version $VERSION...
#cd to vcf root dir
cd ../

#find all files

SRC_DIRS=./src ./build

find $SRC_DIRS -iname '*.h' -o -iname '*.hpp' -o -iname '*.c' \
	-o -iname '*.dsw' -o -iname '*.dsp' -o -iname '*.bmp' -o -iname '*.xml' \
	-o -iname '*.rgs' -o -iname '*.rc' -o -iname '*.idl' > srcfiles.out
	
find $SRC_DIRS -iname '*.def' -o -iname '*.vcfdir' -o -iname '*.vcp' \
	-o -iname '*.ico' -o -iname '*.rc2' -o -iname '*.odl' -o -iname '*.vff' \
	-o -iname '*.inf' -o -iname '*.vcproj' > srcfiles1.out
	
find $SRC_DIRS -iname '*.cpp' -o -iname '*.CPP' -o -iname '*.HPP' \
	-o -iname *.cxx -o -iname '*.CXX' -o -iname '*.cur' \
	-o -iname '*.CUR' -o -iname '*.inl'  > srcfiles2.out

find ./examples -iname '*.h' -o -iname '*.cpp' -o -iname '*.CPP' \
	-o -iname '*.dsw' -o -iname '*.dsp' -o -iname '*.bmp' \
	-o -iname '*.rgs' -o -iname '*.rc' -o -iname '*.idl' \
	-o -iname '*.def' -o -iname '*.ico' -o -iname '*.rc2' \
	-o -iname '*.odl' -o -iname '*.vff' -o -iname '*.html' -o -iname '*.xml' > examples.out

MAKE_FILES="./build/make/Makefile \n\
./build/make/ApplicationKit.mak \n\
./build/make/FoundationKit.mak \n\
./build/make/GraphicsKit.mak \n\
./build/make/LibAGG.mak \n\
./build/make/RemoteObjectKit.mak \n\
./build/make/NetworkKit.mak \n\
./build/make/OpenGLKit.mak \n\
./build/make/Makefile.mak "


#combine the outoput into a master list
echo -e $MAKE_FILES > mkfiles.out
cat srcfiles.out srcfiles1.out srcfiles2.out tests.out examples.out mkfiles.out > files.out

rm srcfiles.out srcfiles1.out srcfiles2.out tests.out examples.out mkfiles.out

#display in notepad
notepad files.out

mkdir tmp
mkdir tmp/vcf-$VERSION

tar -cf tmp/vcf-$VERSION/tmp.tar -T files.out

tar -xf tmp/vcf-$VERSION/tmp.tar -C tmp/vcf-$VERSION/

rm files.out
rm tmp/vcf-$VERSION/tmp.tar

cp --parents readme.txt tmp/vcf-$VERSION/
cp --parents license.txt tmp/vcf-$VERSION/

echo Creating tar file...
cd tmp
tar -cf vcf-$VERSION.tar vcf-$VERSION/

echo Compressing tar file with gzip...
gzip -f vcf-$VERSION.tar

if ( test -d ../uploadToSF/ )
then 
	mv vcf-$VERSION.tar.gz ../uploadToSF/vcf-$VERSION.tar.gz
else
	mv vcf-$VERSION.tar.gz ../
fi

cd ../
rm -rf tmp

echo Done ! 