#ifndef _VCF_NOIMPLEMENTERFOUNDEXCEPTION_H__
#define _VCF_NOIMPLEMENTERFOUNDEXCEPTION_H__
//NoImplementerFoundException.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */

#include "vcf/FoundationKit/BasicException.h"

class NoImplementerFoundException : public VCF::BasicException {

};


/**
*CVS Log info
*$Log$
*Revision 1.2  2004/08/07 02:49:13  ddiego
*merged in the devmain-0-6-5 branch to stable
*
*Revision 1.1.2.2  2004/04/29 04:07:08  marcelloptr
*reformatting of source files: macros and csvlog and copyright sections
*
*/


#endif // _VCF_NOIMPLEMENTERFOUNDEXCEPTION_H__


