#ifndef _VCF_CHECKBOXCONTROL_H__
#define _VCF_CHECKBOXCONTROL_H__
//CheckBoxControl.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */


#include "vcf/ApplicationKit/ToggledButton.h"

namespace VCF{

#define CHECKBOXCONTROL_CLASSID		"7B6F28B3-3E3F-11d4-B555-00C04F0196DA"

/**
\class CheckBoxControl CheckBoxControl.h "vcf/ApplicationKit/CheckBoxControl.h"
*A CheckBoxControl is a control that displays its state with a
*check mark indicating an on/off or true/false state.
*
*/
class APPLICATIONKIT_API CheckBoxControl : public ToggledButton {
public:

	CheckBoxControl();

	virtual ~CheckBoxControl();

	virtual void paint( GraphicsContext* context );

	virtual double getPreferredHeight();

	virtual double getPreferredWidth();

	virtual bool generatePropertyValue( const String& fullPropertyName, Property* property, VariantData* value, String& strValue );
protected:


};

};


#endif // _VCF_CHECKBOXCONTROL_H__

/**
$Id$
*/
