#ifndef _VCF_DATAOBJECTPEER_H__
#define _VCF_DATAOBJECTPEER_H__
//DataObjectPeer.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */



namespace VCF{

class DataObject;

/**
\class DataObjectPeer DataObjectPeer.h "vcf/ApplicationKit/DataObjectPeer.h"
*/
class APPLICATIONKIT_API DataObjectPeer {
public:
	virtual ~DataObjectPeer(){};

    /**
    * Adds a new data type that the dataobject supports.
	*/
    virtual void addSupportedData( const unsigned long & dataType, DataObject* data )=0;

	virtual DataObject* getSupportedData( const unsigned long & dataType )=0;

    /**
     * is the data type passed in supported by the data object ?
     */
    virtual bool isTypeSupported( const unsigned long & dataType )=0;


};

}


#endif // _VCF_DATAOBJECTPEER_H__

/**
$Id$
*/
