#ifndef _VCF_POPUPMENU_H__
#define _VCF_POPUPMENU_H__
//PopupMenu.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */



namespace VCF{

class PopupMenuPeer;

class Control;

#define POPUPMENU_CLASSID		"DDC5AE1F-89CD-4eca-98D4-9ECEFF7B7689"
/**
\class PopupMenu PopupMenu.h "vcf/ApplicationKit/PopupMenu.h"
This class is for creating popup menus, sometimes 
referred to as a context, or contextual menu. Generally
it used when the user right clicks on a control. 
*/
class APPLICATIONKIT_API PopupMenu : public Menu {
public:

	PopupMenu( Control* control=NULL );

	PopupMenu( Component* owner );

	PopupMenu( const String& name, Component* owner );

	PopupMenu( const String& name );

	virtual ~PopupMenu();

	/**
	This "pops up" a context menu and shows it to the user.
	If the user clicks on a menu item in the popup menu, that
	menu item is returned. Keep in mind that the menu item is 
	"owned" by the popup menu instance, and is destroyed when
	the popup menu is.
	@return MenuItem returns a pointer to the menu item that
	the user selected, or NULL if the user dismissed the popup
	menu without clicking on any menu item.
	*/
	virtual MenuItem* popup( Point* pt );

	void setControl( Control* control );
protected:

	void init();

	virtual void destroy();

	PopupMenuPeer* popupPeer_;	
};

};


#endif // _VCF_POPUPMENU_H__

/**
$Id$
*/
