#ifndef _VCF_TREECONTROL_H__
#define _VCF_TREECONTROL_H__
//TreeControl.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */




#ifndef _VCF_TREEMODEL_H__
#	include "vcf/ApplicationKit/TreeModel.h"
#endif // _VCF_TREEMODEL_H__

#ifndef _VCF_TREEITEM_H__
#	include "vcf/ApplicationKit/TreeItem.h"
#endif // _VCF_TREEITEM_H__




namespace VCF {


class TreePeer;
class TreeItem;
class ImageList;

class ModelEvent;


#define TREECONTROL_CLASSID			"ED88C09C-26AB-11d4-B539-00C04F0196DA"

#define TREEITEM_SELECTED	CUSTOM_EVENT_TYPES + ITEM_CONST + 20
#define TREEITEM_EXPANDED	CUSTOM_EVENT_TYPES + ITEM_CONST + 21

/**
\class TreeControl TreeControl.h "vcf/ApplicationKit/TreeControl.h" 
*/
class APPLICATIONKIT_API TreeControl : public VCF::Control, public TreeController {
public:

	TreeControl();
	virtual ~TreeControl();


	enum TreeControlEvents {
		ITEM_STATECHANGE_REQUESTED = CUSTOM_EVENT_TYPES + ITEM_CONST + 10
	};

	DELEGATE(ItemDelegate,ItemSelected);
	DELEGATE(ItemDelegate,ItemStateChangeRequested);
	DELEGATE(ItemDelegate,ItemExpanded);

	virtual void handleEvent( Event* event );

	double getItemIndent();

	void setItemIndent( const double& indent );	

	virtual void modelChanged( Model* oldModel, Model* newModel );

	TreeModel* getTreeModel();

	void setTreeModel( TreeModel* tm );

	ImageList* getImageList();

	ImageList* getStateImageList();

	void setImageList( ImageList* imageList );

	void setStateImageList( ImageList* imageList );

	virtual void paint( GraphicsContext * context );

	void init();

	TreeItem* findItem( Point* pt );

	virtual TreeItem* getItemParent( TreeItem* item );
	virtual void setItemParent( TreeItem* item, TreeItem* parent );

	virtual Rect getItemRect( TreeItem* item );

	virtual void addChildItem( TreeItem* item, TreeItem* child );
	virtual void removeChildItem( TreeItem* item, TreeItem* child );

	virtual TreeItem* getItemFromKey( const TreeModel::Key& key );
	virtual void setItemKey( TreeItem* item, const TreeModel::Key& key );

	virtual bool getItemChildren( TreeItem* item, std::vector<TreeItem*>& children );

	virtual void insertItemSubItem( TreeItem* item, const uint32& index, TreeSubItem* subItem );
	virtual void removeItemSubItem( TreeItem* item, TreeSubItem* subItem );
	virtual bool getItemSubItems( TreeItem* item, std::vector<TreeSubItem*>& subItems );
	virtual TreeSubItem* getItemSubItem( TreeItem* item, const uint32& index );
	virtual uint32 getItemSubItemCount( TreeItem* item );

	virtual void itemExpanded( TreeItem* item );
	virtual void itemSelected( TreeItem* item );


	void insertItem( TreeItem* parent, TreeItem* item );
	TreeItem* insertItem( TreeItem* parent, const String& caption, const uint32 imageIndex=0 );

	void removeItem( TreeItem* item );

	TreeItem* getSelectedItem();

	Rect getItemImageRect( TreeItem* item );

	

	bool getAllowLabelEditing();

	void setAllowLabelEditing( const bool& allowLabelEditing );

	virtual uint64 sizeOf() const;

	bool itemExists( const TreeModel::Key& key );
protected:
	TreeItem* hitTestForItem( Point* pt, TreeItem* item );

	void onTreeItemPaint( ItemEvent* event );	

	//void onTreeNodeAdded( TreeModelEvent* event );

	//void onTreeNodeDeleted( TreeModelEvent* event );

	void onModelChanged( ModelEvent* event );


	TreePeer * treePeer_;
	ImageList* imageList_;
	ImageList* stateImageList_;
	TreeItem* currentSelectedItem_;
	bool controlChangeToModel_;
	std::map<TreeModel::Key,TreeItem*> itemMap_;


};

}; //namespace VCF


#endif // _VCF_TREECONTROL_H__

/**
$Id$
*/
