#!/bin/bash

echo Preparing list of files for vcf version $1...
#cd to vcf root dir
cd ../

#find all files

SRC_DIRS=../../include ../../src ../../ImageFormats ../../build ../../AppServer ../../xmake ../../ClassServer ../../thirdparty

find $SRC_DIRS -iname '*.h' -o -iname '*.hpp' -o -iname '*.c' \
	-o -iname '*.dsw' -o -iname '*.dsp' -o -iname '*.bmp' -o -iname '*.xml' \
	-o -iname '*.rgs' -o -iname '*.rc' -o -iname '*.idl' > srcfiles.out
	
find $SRC_DIRS -iname '*.def' -o -iname '*.vcfdir' -o -iname '*.vcp' \
	-o -iname '*.ico' -o -iname '*.rc2' -o -iname '*.odl' -o -iname '*.vff' \
	-o -iname '*.inf' -o -iname '*.vcproj' > srcfiles1.out
	
find $SRC_DIRS -iname '*.cpp' -o -iname '*.CPP' -o -iname '*.HPP' \
	-o -iname *.cxx -o -iname '*.CXX' -o -iname '*.cur' \
	-o -iname '*.CUR' -o -iname '*.inl'  > srcfiles2.out

find ./examples -iname '*.h' -o -iname '*.cpp' -o -iname '*.CPP' \
	-o -iname '*.dsw' -o -iname '*.dsp' -o -iname '*.bmp' \
	-o -iname '*.rgs' -o -iname '*.rc' -o -iname '*.idl' \
	-o -iname '*.def' -o -iname '*.ico' -o -iname '*.rc2' \
	-o -iname '*.odl' -o -iname '*.vff' -o -iname '*.html' -o -iname '*.xml' > examples.out

MAKE_FILES="./build/make/Makefile \n\
./build/make/ApplicationKitObjects.mak \n\
./build/make/FoundationKitObjects.mak \n\
./build/make/GraphicsKitObjects.mak \n\
./build/make/LibAGGObjects.mak \n\
./build/make/NetworkKitObjects.mak \n\
./build/make/common.mak "


#combine the outoput into a master list
echo -e $MAKE_FILES > mkfiles.out
cat srcfiles.out srcfiles1.out srcfiles2.out tests.out examples.out mkfiles.out > files.out

rm srcfiles.out srcfiles1.out srcfiles2.out tests.out examples.out mkfiles.out

#display in notepad
notepad files.out

mkdir tmp
mkdir tmp/vcf-$1

tar -cf tmp/vcf-$1/tmp.tar -T files.out

tar -xf tmp/vcf-$1/tmp.tar -C tmp/vcf-$1/

rm files.out
rm tmp/vcf-$1/tmp.tar

cp --parents readme.txt tmp/vcf-$1/
cp --parents license.txt tmp/vcf-$1/

echo Creating tar file...
cd tmp
tar -cf vcf-$1.tar vcf-$1/

echo Compressing tar file with gzip...
gzip -f vcf-$1.tar

if ( test -d ../uploadToSF/ )
then 
	mv vcf-$1.tar.gz ../uploadToSF/vcf-$1.tar.gz
else
	mv vcf-$1.tar.gz ../
fi

cd ../
rm -rf tmp

echo Done ! 