//BasicException.cpp

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


/* Generated by Together */

#include "vcf/FoundationKit/FoundationKit.h"
using namespace VCF;


BasicException::BasicException(const String & message)
{
	this->message_ = message;
	System::print( message_ );
}

BasicException::BasicException( const VCF::String & message, const int lineNumber )
{
	this->message_ = message;
#ifdef _DEBUG
	char txt[256];
	sprintf( txt, "\nerror at line number %d", lineNumber );
	this->message_ += txt;
#endif
	System::print( message_ );
}

String BasicException::getMessage()
{
	return this->message_;
}

void BasicException::setMessage( const VCF::String& message )
{
	this->message_ = message;
}


/**
*CVS Log info
*$Log$
*Revision 1.2  2004/08/07 02:49:12  ddiego
*merged in the devmain-0-6-5 branch to stable
*
*Revision 1.1.2.2  2004/04/29 04:07:05  marcelloptr
*reformatting of source files: macros and csvlog and copyright sections
*
*/


