#ifndef _VCF_FILENOTFOUND_H__
#define _VCF_FILENOTFOUND_H__
//FileNotFound.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */




namespace VCF{
/**
\class FileNotFound FileNotFound.h "vcf/FoundationKit/FileNotFound.h"
*/
class FOUNDATIONKIT_API FileNotFound : public BasicFileError {
public:
	FileNotFound( const String & message ):
		BasicFileError( message ){};

		virtual ~FileNotFound() throw() {};
};

};


#endif // _VCF_FILENOTFOUND_H__

/**
$Id$
*/
