#ifndef _VCF_NOFREEMEMEXCEPTION_H__
#define _VCF_NOFREEMEMEXCEPTION_H__
//NoFreeMemException.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */


namespace VCF {
/**
\class NoFreeMemException NoFreeMemException.h "vcf/FoundationKit/NoFreeMemException.h"
*/
class FOUNDATIONKIT_API NoFreeMemException : public BasicException {
public:
	NoFreeMemException( const String & message ):
	  BasicException( message ){};

	NoFreeMemException():
		BasicException( NO_FREE_MEMORY_AVALIABLE ){};

	NoFreeMemException( const String & message, const int lineNumber ):
		BasicException(message, lineNumber){};

	virtual ~NoFreeMemException() throw() {};
};

};


#endif // _VCF_NOFREEMEMEXCEPTION_H__

/**
$Id$
*/
