#ifndef _VCF_ELLIPSE_H__
#define _VCF_ELLIPSE_H__
//Ellipse.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */



namespace VCF{

class GRAPHICSKIT_API Ellipse : public BezierCurve {
};

};


#endif // _VCF_ELLIPSE_H__

/**
$Id$
*/
